name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', depending on your repo

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # Upload the entire root folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

