name: Deploy Static Website to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6

      - name: Upload files
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: .  # Adjust if your site is in a subfolder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2.0.4


